### ISSUE TITLE
Provide Riemann callbacks for the pluggable onyx-metrics

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-metrics#4]
[Onyx Op Metrics](https://github.com/onyx-platform/onyx/blob/master/doc/user-guide/monitoring.md#monitoring-hooks) provides a bunch of useful latency/throughput metrics that I would love to see in Riemann. 

We should provide a callback function for sending monitoring events to Riemann

**Comment by MichaelDrogalis** [comment]
It'd be great to have a library for this that you can automatically bring in.

**Comment by gardnervickers** [comment]
Separate from onyx-metrics?

**Comment by MichaelDrogalis** [comment]
Yeah. Preferably the library would expose a set of functions to do the callbacks. It would also `def` a var that would be a map of keyword to function, so the user would only need to require the file with the `def` in it and supply it as the monitoring configuration. Haven't thought through this 100% though.

**Comment by gardnervickers** [comment]
Alright I see where you're coming from. Keep onyx-platform/onyx-metrics primarily concerned with job-level metrics, make an external library for Onyx-level metrics.

**Comment by MichaelDrogalis** [comment]
Exactly. :)
